### PR TITLE
Fixes #2 - Add clickable GitHub link.

### LINKED ISSUE #2: Links are not clickable
**Description:**
Right now links in `Admin` not clickable

**Actual Beahviour**
image

**Expected Behaviour**
Links should be clickable and when clicked should open in new tab

### PR DESCRIPTION
**Pull request by hawtre**
Fixes #2 - Add clickable GitHub link.

### CODE REVIEW

**Comment by vaibhavsingh97** [comment]
@hawtre Thanks for contributing 🌟 
Can you please make the links open in new tab 😄 You just have to add `target="_blank"`

**Comment by vaibhavsingh97** [comment]
Can you please fix https://www.codacy.com/app/vaibhavsingh97/OpenSourceSession/pullRequest?prid=955706&/login. Rest you have done awesome work 🎉

**Comment by vaibhavsingh97** [comment]
@hawtre Please fix conflicts and squash your commits. Then this PR is ready to merge 😄

**Comment by vaibhavsingh97** [comment]
@hawtre Still conflicts are there

**Comment by hawtre** [comment]
Sorry, do you want the merge commit from origin?

**Comment by vaibhavsingh97** [comment]
@hawtre Can you please squash commits into one

**Comment by vaibhavsingh97** [comment]
@hawtre Don't give up, you just have to squash commits and merge conflicts 😄

**Comment by vaibhavsingh97** [comment]
Closing since this issue is fixed. Thanks for contributing 😄
You can look into existing issue [here](https://github.com/vaibhavsingh97/OpenSourceSession/issues)

**Pull request closed without merging**
