### PR TITLE
Linkify email and GitHub URL

### LINKED ISSUE #2: Links are not clickable
**Description:**
Right now links in `Admin` not clickable

**Actual Beahviour**
image

**Expected Behaviour**
Links should be clickable and when clicked should open in new tab

### PR DESCRIPTION
**Pull request by bryanjhv**
Fixes #2 and code linted with PEP8.

### CODE REVIEW

**Comment by vaibhavsingh97** [comment]
@bryanjhv Thank you for contributing, You had done awesome job 🎉. Since Hawtre made the PR first so i think we should give him the fair chance. Let his PR merge and rebase send the PR to make the email link clickablev 😄 Hope you understand my point.

**Comment by bryanjhv** [comment]
Yeah! I agree with you. But when will that PR be merged? 😅

**Comment by vaibhavsingh97** [comment]
@bryanjhv Please fix conflicts, i will merge PR right now 😄

**Comment by vaibhavsingh97** [comment]
@bryanjhv Thanks for contributing 😄. You can starr this if you like it and yes sorry from my side that i haven't merged this PR.

**Comment by bryanjhv** [comment]
Thanks! I'll be looking if I can contribute other things also. 😃

**Comment by vaibhavsingh97** [comment]
@bryanjhv Why you don't join FOSSASIA 😄

**Pull request merged**
